apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: karunnyi-ambulance-ufe-content
spec:
  microFrontend: karunnyi-ambulance-ufe
  element: karunnyi-ambulance-wl-app
  attributes:
    - name: base-path
      value: /karunnyi-ambulance-wl/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?karunnyi-ambulance-wl(/.*)?$"