kind: Service
apiVersion: v1
metadata:
  name: karunnyi-openapi-ui
spec:
  selector:
    pod: karunnyi-ambulance-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8081